name: Metrics
on:
  schedule:
    - cron: "0 0-23/6 * * *"
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: 🦑 Personal metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, scala, c, ejs
          plugin_languages_details: bytes-size, percentage
          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_mode: mastered
          config_order: base.header, isocalendar, languages, notable, topics
          

      - name: 🦑 Personal metrics (anilist)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.personal.anilist.svg
          token: NOT_NEEDED
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          plugin_anilist: yes
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: watching, favorites, characters
          plugin_anilist_limit: 3
          plugin_anilist_limit_characters: 22
          plugin_anilist_shuffle: true

      - name: ⏰ WakaTime plugin
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.wakatime.svg
          token: NOT_NEEDED
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          use_mocked_data: yes
          plugins_errors_fatal: ${{ github.repository == 'insaiyancvk/insaiyancvk' }}
