name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    - uses: lowlighter/metrics@v3.8
      with:
        token: ${{ secrets.METRICS_TOKEN }}
        # Metrics base content
        base: header, activity, community, repositories, metadata # optional, default is header, activity, community, repositories, metadata
        # Number of repositories to use
        repositories: 100 # optional, default is 100
        # GitHub Personal Token
        # token: ${{ secrets.GITHUB_TOKEN }}
        # GitHub username
        user: insaiyancvk # optional, default is 
        # GitHub repository
        repo: insaiyancvk # optional, default is 
        # GitHub Token used to commit metrics
        committer_token: ${{ github.token }} # optional, default is ${{ github.token }}
        # Branch used to commit rendered metrics
        committer_branch: main # optional, default is 
        # Commit message
        committer_message: Update ${filename} - [Skip GitHub Action] # optional, default is Update ${filename} - [Skip GitHub Action]
        # Rendered metrics output path
        filename: github-metrics.* # optional, default is github-metrics.*
        # Rendered markdown output path
        markdown: TEMPLATE.md # optional, default is TEMPLATE.md
        # Rendered markdown file cache
        markdown_cache: .cache # optional, default is .cache
        # Output action
        output_action: commit # optional, default is commit
        # SVG optimization
        optimize: true # optional, default is true
        # Template to use
        template: classic # optional, default is classic
        # SVG CSS animations
        config_animations: true # optional, default is true
        # Image padding
        config_padding: 6%, 13% # optional, default is 6%, 13%
        # Output image format
        config_output: auto # optional, default is auto
        # Number of retries
        retries: 3 # optional, default is 3
        # Time to wait (in seconds) before each retry
        retries_delay: 300 # optional, default is 300
        plugin_lines: yes
        plugin_music: yes
        plugin_music_limit: 4
        plugin_music_playlist: https://open.spotify.com/embed/playlist/1RkDFCqGrtxsrrydwgqqjG
        plugin_music_provider: spotify # Use Spotify as provider
        plugin_music_mode: recent      # Set plugin mode
        plugin_music_played_at: yes    # Show timestamp (for spotify only)
        plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
        # Display data from your AniList account
        plugin_anilist: yes # optional
        # Medias types to display
        plugin_anilist_medias: anime, manga # optional, default is anime, manga
        # Sections to display
        plugin_anilist_sections: watching, characters # optional, default is favorites
        # Maximum number of entries to display per section
        plugin_anilist_limit: 2 # optional, default is 2
        # Maximum number of entries to display in characters section
        plugin_anilist_limit_characters: 22 # optional, default is 22
        # Shuffle AniList data
        plugin_anilist_shuffle: true # optional, default is true
        # AniList login
        plugin_anilist_user: .user.login # optional, default is .user.login
        # Display WakaTime stats
        plugin_wakatime: yes # optional
        # WakaTime API token
        plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }} # optional, default is 
        # WakaTime time range
        plugin_wakatime_days: 7 # optional, default is 7
        # Sections to display
        plugin_wakatime_sections: time, projects, projects-graphs, languages, os # optional, default is time, projects, projects-graphs, languages, languages-graphs, editors, os
        # Maximum number of entries to display per graph
        plugin_wakatime_limit: 5 # optional, default is 5
        # Address where to reach your Wakatime instance
        plugin_wakatime_url: https://wakatime.com # optional, default is https://wakatime.com
        # Your Wakatime user on the selfhosted Wakapi instance
        plugin_wakatime_user: .user.login # optional, default is .user.login
